{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
#  {{- if .Values.hpaAnnotations.enabled }}
#  annotations:
#    metric-config.external.prometheus-query.prometheus/prometheus-server: {{ .Values.hpaAnnotations.prometheusServer }}
#    metric-config.external.prometheus-query.prometheus/istio-requests-total: |
#      sum(rate(istio_requests_total{reporter="destination", destination_workload=~"{{ .Release.Name }}|{{ .Release.Name }}-primary", destination_service_namespace="{{ .Release.Namespace }}"}[2m]))
#  {{- end }}
  labels:
    {{- include "base.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
  - type: Pods
    pods:
      metric:
        name: istio_requests_per_second
      target:
        type: AverageValue
        averageValue: "{{ .Values.autoscaling.QPStarget }}"
    # {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    # - type: Resource
    #   resource:
    #     name: cpu
    #     targetAverageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    # {{- end }}
    # {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    # - type: Resource
    #   resource:
    #     name: memory
    #     targetAverageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    # {{- end }}
{{- end }}
