{{- if or .Values.authToken .Values.joinParams.tokenName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Release.Namespace }}
{{- if .Values.extraLabels.secret }}
  labels:
  {{- toYaml .Values.extraLabels.secret | nindent 4 }}
{{- end }}
type: Opaque
stringData:
  auth-token: |
    {{ coalesce .Values.joinParams.tokenName .Values.authToken }}
{{- end }}
